language: python
dist : trusty
python:
- '3.5.1'
addons:
  postgresql: "9.6"
before_install:
  - export DJANGO_SETTINGS_MODULE=BunqWebApp.settings
  - export PYTHONPATH=$HOME/builds/OGKevin/ComBunqWebApp
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install --production
before_script:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - ./manage.py migrate
  - ./manage.py collectstatic --noinput -v 0
script:
  - coverage run ./manage.py test
deploy:
  provider: heroku
  api_key:
    secure: r2as3e8N198Pz7Th3kpxC/d1JMigwd5wtVvb7t8focibhkf4l+QxqpmS9LU/gI5CXn3eI3NIog1R7bXlORGuevr3+2uY2D7pv/DwagvSuUi8kJsbKtUHRqw+NBIhLoiQbYX1ER9CQ6EIiVtRjbTqgWFy0zYPKnhloVNmKtqpZgv35LMi1oaCntXea1EgOSoNnxtTE/2vc7bQGr5bZf2m8upe0d3gb1booRO/frBGU1nNwzcN6p1G1B73P3rNHyfB0WFT1Edeu+MYVOnrgX4yBjCg92qNXW2R+VAqeT+MgdWwGQO33HQCK/+V3LDMVsp9xYIlxGyO9T7ij8cJBlekK53ITTzjS3GZbP+GnOaUlpD53Yb+s0RQhA3mAo+wc0zw112+5QCPFlKAtTMZE5Bw5cXUPS2bI5YG+5q8otS9DiwPgNeN9CbrooP2mrBLkwyOI2yWe5pwE/Y7xfsNcnEzK0rNR117XZTHC6z/MSF/XVYNE16xiuAZ6G3w2K1loQl2pMSr32eAKDYPaEiQ68XTSVOKQUCgq9D3N29E472PJIgXP+CurVrMpHkizD8RYhplKftkIAktgZHhN3AxetrTxn/6N3J3KS6j89Q+7n5U5Q/lLAuvRtXPGJR5fKin56Cu5LIZmFOeOAMupBJHXWvbEY0oLaELBZUumlVerv3F9Zs=
  run :
    - "./manage.py migrate"
    - restart
  app : combunqweb
  on:
    tags: true
  
after_success:
  - coveralls
